# NumPy

- Numerical Python
- N dimensional array used for processing 
- Supports different data types

# Array 

 - An Array is a datastructure that stores values of the same data type
 - Lists can contain different data types

# NumPy Array

- A numpy array is a grid of values, all of the same datatype, and is indexed by a tuple of non-negative integers
- The number of dimensions is the rank of the array.
- The shape of the array is a tuple of integers giving the size of the array across each dimension
- Mathematical and scientific computing can be performed easily using np arrays

# Creation of Array

In [14]:
my_list = [i+1 for i in list(range(6))]
print(my_list)

[1, 2, 3, 4, 5, 6]





## To create numpy array, we need to import it 

In [5]:
import numpy as np

In [15]:
array = np.array(my_list, dtype=int)
print(array)

[1 2 3 4 5 6]


In [16]:
print(type(array))
print(len(array)) # number of elements in the array
print(array.ndim) # number of axis in the array
print(array.shape) # Size along each dimension

<class 'numpy.ndarray'>
6
1
(6,)


In [17]:
array2 = array.reshape(3,2)
print(array2)

print(array.ndim)


[[1 2]
 [3 4]
 [5 6]]
1


In [18]:
def numbers(n):
    return [i+1 for i in range(n) ]

In [19]:
x = numbers(5)

In [20]:
x

[1, 2, 3, 4, 5]

In [24]:
array3 = np.array(x, dtype=int)

In [25]:
array3

array([1, 2, 3, 4, 5])

In [26]:
type(array3)

numpy.ndarray

In [28]:
array3.reshape(5,-1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [32]:
# Numpy array from nested python list

myList1 = numbers(5)
myList2 = [i*2 for i in numbers(5)]
myList3 = [i*5 for i in numbers(5)]

print(myList1)
print(myList2)
print(myList3)

mul_arr = np.array([myList1, myList2, myList3])
print(mul_arr)

print(mul_arr.shape)

[1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]
[5, 10, 15, 20, 25]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 5 10 15 20 25]]
(3, 5)


In [33]:
mul_arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  5, 10, 15, 20, 25]])

# Numpy attributes

In [36]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [35]:
print(a.shape)

(2, 3)


In [37]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [39]:
a.shape = (3,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [41]:
a.reshape(6,4,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

# Numpy Arithmetic Operations

In [42]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]


## numpy.add() - performs elementwise addition between two arrays

- Syntax: numpy.add(array_1,array_2)

In [43]:
print(x+y)
print(np.add(x,y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


## numpy.subtract() - performs elementwise subtraction between two arrays

- Syntax: numpy.subtract(array1,array2)

In [44]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


## numpy.multiply() - performs elementwise multiplication between two arrays

- Syntax: numpy.multiply(array1,array2)

In [45]:
print(x*y)
print(np.multiply(x,y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


# for dot product: Matrix Multiplication

In [47]:
print(x.dot(y))
print(np.dot(x,y))

[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]


In [48]:
print(x)
print(y)

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]


In [49]:
print(x/y)

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [53]:
print(np.mod(y,x))

[[ 0.  0.]
 [ 1.  0.]]


# sum of all array elements over the given axis

In [54]:
print(x)

[[ 1.  2.]
 [ 3.  4.]]


In [55]:
print(np.sum(x))

10.0


In [58]:
print(np.sum(x,1)) # 1 represents performing sum across the rows

[ 3.  7.]


In [60]:
print(np.sum(x,axis=0)) # 0 represents performing sum accross the columns

[ 4.  6.]


# we can do similar options using mean, median and mode